### ISSUE TITLE
Add template to generate indexes

### ISSUE THREAD

**Issue by keithbloom** [chucknorris/powerup#14]

**Comment by StevenLiekens** [comment]
I'm looking at adding support for indexes. Currently it is not feasible to add index templates. The existing classes heavily depend on the structure of the `sys.objects` table. User-defined indexes are not database objects!

The object model needs to be rewritten so that `IQueryBase.TextSql` is replaced with a method that executes an implementation-specific query.

**Comment by keithbloom** [comment]
Hi. Supporting index creation is a sound idea and thanks for creating the PR. I"ll take a look this week and get it merged in.

**Comment by StevenLiekens** [comment]
Thanks! Let me know if you have any doubts about what I changed.

**Comment by StevenLiekens** [comment]
I just found out that there is a recommended template for indexes over here: https://github.com/chucknorris/roundhouse/wiki/Anytimescripts

The code in my pull request does not use this template, but I'd like to change the code so that it does. Please don't merge this yet.
